Update docs
cycloid-community-catalog/stack-concourse-server pull request #2
Opened 2019-04-18 15:54 UTC by gaelL

2019-04-18 16:15 UTC, sdurrheimer commented on pipeline/variables.sample.yml
> +#+ Password used for your rds database.
```suggestion
#+ Password used for your RDS database.
```

2019-04-18 16:15 UTC, sdurrheimer commented on pipeline/variables.sample.yml
> +#+ Git repository url containing the config of the stack.
```suggestion
#+ Git repository URL containing the config of the stack.
```

2019-04-18 16:15 UTC, sdurrheimer commented on pipeline/variables.sample.yml
> +#+ Branch of the config git repository.
```suggestion
#+ Branch of the config Git repository.
```

2019-04-18 16:15 UTC, sdurrheimer commented on pipeline/variables.sample.yml
> +#+ SSH key pair to fetch the config git repository.
```suggestion
#+ SSH key pair to fetch the config Git repository.
```

2019-04-18 16:15 UTC, sdurrheimer commented on pipeline/variables.sample.yml
> +#+ Public ssh key injected by Packer during the build of the AMI for debug purpose
```suggestion
#+ Public SSH key injected by Packer during the build of the AMI for debug purpose
```

2019-04-18 16:15 UTC, sdurrheimer commented on pipeline/variables.sample.yml
> +#+ Version of ansible used during Packer build to run Ansible playbook
```suggestion
#+ Version of Ansible used during Packer build to run Ansible playbook
```

2019-04-18 16:15 UTC, sdurrheimer commented on pipeline/variables.sample.yml
> +#+ Branch to use on the public stack git repository
```suggestion
#+ Branch to use on the public stack Git repository
```

2019-04-18 16:15 UTC, sdurrheimer commented on pipeline/variables.sample.yml
> +#+ Path of Ansible files in the config git repository
```suggestion
#+ Path of Ansible files in the config Git repository
```

2019-04-18 16:15 UTC, sdurrheimer commented on pipeline/variables.sample.yml
> +#+ Path of Terraform files in the config git repository
```suggestion
#+ Path of Terraform files in the config Git repository
```

2019-04-18 16:15 UTC, sdurrheimer commented on terraform/concourse-server.tf.sample
> +  #+ Amazon source security group ID which will be allowed to connect on Magento front port 22 (ssh)
```suggestion
  #+ Amazon source security group ID which will be allowed to connect on Magento front port 22 (SSH)
```

2019-04-18 16:15 UTC, sdurrheimer commented on terraform/concourse-server.tf.sample
> +  #+ SSH keypair name to use to deploy ec2 instances
```suggestion
  #+ SSH keypair name to use to deploy EC2 instances
```

2019-04-18 16:15 UTC, sdurrheimer commented on terraform/concourse-server.tf.sample
> +  #+ Root disk size in Go of Aws EC2 concourse servers.
```suggestion
  #+ Root disk size in Go of AWS EC2 concourse servers.
```

2019-04-18 16:15 UTC, sdurrheimer commented on terraform/concourse-server.tf.sample
> +  #+ Volume disk size in Go of Aws EC2 concourse servers.
```suggestion
  #+ Volume disk size in Go of AWS EC2 concourse servers.
```

2019-04-18 16:15 UTC, sdurrheimer commented on terraform/concourse-server.tf.sample
> +  #+ Type of Aws EC2 concourse servers. This will be used for "spot" and "ondemand" launch config templates
```suggestion
  #+ Type of AWS EC2 concourse servers. This will be used for "spot" and "ondemand" launch config templates
```

2019-04-18 16:15 UTC, sdurrheimer commented on terraform/concourse-server.tf.sample
> +  #+ Assosiate or not an Amazon public IP to concourse servers.
```suggestion
  #+ Assosiate or not an Amazon public IP to Concourse servers.
```

2019-04-18 16:15 UTC, sdurrheimer commented on terraform/concourse-server.tf.sample
> +  #+ Create a dedicated ALB on top of concourse servers.
```suggestion
  #+ Create a dedicated ALB on top of Concourse servers.
```

2019-04-23 12:30 UTC, xlr-8 requested changes
Made couple suggestions/comments

2019-04-23 12:30 UTC, xlr-8 commented on README.md
> +
I'd reorder by jobs order.
The deploy AMI isn't present here, is it still required after an apply, or forgotten?

2019-04-23 12:30 UTC, xlr-8 commented on README.md
>  Built on the simple mechanics of resources, tasks, and jobs, Concourse presents a general approach to automation that makes it great for CI/CD.
```suggestion
Built on the simple mechanics of resources, tasks, and jobs. Concourse presents a general approach to automation that makes it great for CI/CD.
```

2019-04-23 12:30 UTC, xlr-8 commented on README.md
> +  * Having a VPC with private & public subnets [Here](https://docs.aws.amazon.com/vpc/latest/userguide/getting-started-ipv4.html#getting-started-create-vpc)
```suggestion
  * Having a VPC with private & public subnets [here](https://docs.aws.amazon.com/vpc/latest/userguide/getting-started-ipv4.html#getting-started-create-vpc)
```

2019-04-23 12:30 UTC, xlr-8 commented on README.md
> +  * Having an S3 bucket to store Terraform remote states [Here](https://docs.aws.amazon.com/quickstarts/latest/s3backup/step-1-create-bucket.html)
```suggestion
  * Having an S3 bucket to store Terraform remote states [here](https://docs.aws.amazon.com/quickstarts/latest/s3backup/step-1-create-bucket.html)
```

2019-04-23 12:30 UTC, xlr-8 commented on README.md
> +|`aws_access_key`|Amazon AWS access key for Terraform. see value format [Here](https://docs.cycloid.io/advanced-guide/integrate-and-use-cycloid-credentials-manager.html#vault-in-the-pipeline)|`-`|`((
```suggestion
|`aws_access_key`|Amazon AWS access key for Terraform. see value format [here](https://docs.cycloid.io/advanced-guide/integrate-and-use-cycloid-credentials-manager.html#vault-in-the-pipeline)|`-`|`((aws.access_key))`|`True`|
```

2019-04-23 12:30 UTC, xlr-8 commented on README.md
> +|`aws_secret_key`|Amazon AWS secret key for Terraform. see value format [Here](https://docs.cycloid.io/advanced-guide/integrate-and-use-cycloid-credentials-manager.html#vault-in-the-pipeline)|`-`|`((
```suggestion
|`aws_secret_key`|Amazon AWS secret key for Terraform. see value format [here](https://docs.cycloid.io/advanced-guide/integrate-and-use-cycloid-credentials-manager.html#vault-in-the-pipeline)|`-`|`((aws.secret_key))`|`True`|
```

2019-04-23 12:30 UTC, xlr-8 commented on README.md
> +> Note: To allow concourse external workers, you will need to their SSH public keys
```suggestion
> Note: To allow concourse external workers, you will need to put their SSH public key
```

2019-04-23 12:30 UTC, xlr-8 commented on README.md
> +> Allowed worker keys in this directory will be assembled into a authorized_keys
```suggestion
> Allowed worker keys in this directory will be assembled into an authorized_keys
```

2019-04-23 12:30 UTC, xlr-8 commented on pipeline/variables.sample.yml
> +#+ Amazon AWS access key for Terraform. see value format [Here](https://docs.cycloid.io/advanced-guide/integrate-and-use-cycloid-credentials-manager.html#vault-in-the-pipeline)
```suggestion
#+ Amazon AWS access key for Terraform. See value format [here](https://docs.cycloid.io/advanced-guide/integrate-and-use-cycloid-credentials-manager.html#vault-in-the-pipeline)
```

2019-04-23 12:30 UTC, xlr-8 commented on pipeline/variables.sample.yml
> +#+ Amazon AWS secret key for Terraform. see value format [Here](https://docs.cycloid.io/advanced-guide/integrate-and-use-cycloid-credentials-manager.html#vault-in-the-pipeline)
```suggestion
#+ Amazon AWS secret key for Terraform. See value format [here](https://docs.cycloid.io/advanced-guide/integrate-and-use-cycloid-credentials-manager.html#vault-in-the-pipeline)
```

2019-05-06 13:23 UTC, merged